<?php

namespace NeigeEtSoleilBundle\Repository;

/**
 * LocatairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocatairesRepository extends \Doctrine\ORM\EntityRepository
{
}
