<?php

namespace NeigeEtSoleilBundle\Repository;

/**
 * ProprietairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProprietairesRepository extends \Doctrine\ORM\EntityRepository
{
}
